name: Build Zeetcord

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/build-zeetcord.yml
      - aliucord/**
      - .assets/data.json

jobs:
  build-zeetcord:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: src

      - name: Checkout builds
        uses: actions/checkout@v4
        with:
          ref: builds
          path: builds

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build Zeetcord
        run: |
          cd $GITHUB_WORKSPACE/src
          ./gradlew :aliucord:make
          cp aliucord/build/zeetcord.zip $GITHUB_WORKSPACE/builds
        # env:
        #   MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
        #   MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}

      - name: Push builds
        run: |
          cd $GITHUB_WORKSPACE/builds
          cp ../src/.assets/AndroidManifest.xml .
          if git diff --exit-code zeetcord.zip >/dev/null; then
            # No changes to Zeetcord.zip, simply merge builds data.json and Zeetcord data.json to keep the old aliucordHash
            jq -s '.[0] * .[1]' data.json ../src/.assets/data.json > data.json.new
            mv data.json.new data.json
          else
            # Changes to Zeetcord.zip, update aliucordHash
            jq ". + { aliucordHash: \"$(git --git-dir=../src/.git rev-parse --short HEAD)\" }" < ../src/.assets/data.json > data.json
          fi
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git pull
          git add .
          git commit -m "Build $GITHUB_SHA"
          git push
