name: Build APK

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/build-injector.yml
      - injector/**

jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: src

      - name: Checkout builds
        uses: actions/checkout@v4
        with:
          ref: builds
          path: builds

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build APK
        run: |
          cd $GITHUB_WORKSPACE/src
          ./gradlew :injector:generateApk
          cp injector/build/zeetcord.apk $GITHUB_WORKSPACE/builds

      - name: Push builds
        run: |
          cd $GITHUB_WORKSPACE/builds
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git pull
          git add .
          git commit -m "Build $GITHUB_SHA"
          git push
