name: PR Artifact

on:
  pull_request:
    paths:
      - .github/workflows/upload-pr-artifact.yml
      - aliucord/**
      - gradle/**
      - settings.gradle
      - gradlew
      - gradle.properties
      - build.gradle

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build Zeetcord
        run: |
          cd $GITHUB_WORKSPACE
          ./gradlew :aliucord:make

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: Zeetcord
          path: aliucord/build/zeetcord.zip
