name: installer
description: Zeetcord Installer

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  android_intent_plus: ^4.0.1
  collection: ^1.17.1
  dio: ^5.3.1
  filesystem_picker: ^4.0.0
  path_provider: ^2.0.15
  shared_preferences: ^2.2.0
  dynamic_color: ^1.6.6

dev_dependencies:
  flutter_lints: ^3.0.0

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  fonts:
    - family: CustomIcons
      fonts:
        - asset: fonts/CustomIcons.ttf
